#define SPRITE_TYPE_WORLD_PIECE 0x10
#define SPRITE_TYPE_IGNORED 0x11
#define SPRITE_TYPE_ENEMY 0x12
#define SPRITE_SIZE_MASK 0xf0
#define SPRITE_PALETTE_MASK 0x03
#define SPRITE_SIZE_NORMAL 0

#define SPRITE_PALETTE_0 0
#define SPRITE_PALETTE_1 1
#define SPRITE_PALETTE_2 2
#define SPRITE_PALETTE_3 3

#define SPRITE_DIRECTION_LEFT 0x24
#define SPRITE_DIRECTION_RIGHT 0x20
#define SPRITE_DIRECTION_UP 4
#define SPRITE_DIRECTION_DOWN 0

#define ENEMY_VELOCITY_LOCK_TIME 20

void banked_draw_sprites();